[versions]
activity-compose = "1.12.4"
agp = "9.0.0"
annotation = "1.9.1"
appcompat = "1.7.1"
assert-k = "0.28.1"
bson = "5.6.3"
coil-compose = "2.7.0"
compose-bom = "2026.02.00"
compose-ui-test-manifest = "1.10.3"
concurrent-futures = "1.3.0"
core-ktx = "1.17.0"
core-splashscreen = "1.2.0"
coroutines = "1.10.2"
coroutines-test = "1.10.2"
desugar-jdk-libs = "2.1.5"
detekt = "2.0.0-alpha.2"
espresso-core = "3.7.0"
glance = "1.1.1"
junit = "4.13.2"
junit5 = "6.1.3"
junit5-compose = "2.0.1"
junit5-plugin = "2.0.1"
junit-version = "1.3.0"
koin = "4.1.1"
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
ksp = "2.3.4"
ktor = "3.4.0"
ktor-client-logging = "3.4.0"
lifecycle-runtime-ktx = "2.10.0"
material = "1.13.0"
material3 = "1.5.0-alpha14"
material-adaptive = "1.2.0"
material-icons-extended = "1.7.8"
mock-k = "1.14.9"
navigation-compose = "2.9.7"
org-jetbrains-kotlin-jvm = "2.3.10"
room = "2.8.4"
security-crypto-ktx = "1.1.0"
timber = "5.0.1"
turbine = "1.2.1"
work = "2.11.1"

# Project Versions
project-application-id = "com.y0x.sexyboard"
project-compile-sdk-version = "36"
project-min-sdk-version = "26"
project-target-sdk-version = "36"
project-version-code = "1"
project-version-name = "1.0"

[libraries]
# Core Libraries
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# AndroidX Libraries
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrent-futures" }
androidx-concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent-futures" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "security-crypto-ktx" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# Compose Libraries
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material-adaptive" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material-adaptive" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }

# 3rd Party Libraries
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
koin-android-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-client-logging" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
org-mongodb-bson = { module = "org.mongodb:bson", version.ref = "bson" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing Libraries
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assert-k" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-android-test-compose = { module = "de.mannodermaus.junit5:android-test-compose", version.ref = "junit5-compose" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mock-k" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mock-k" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "dev.detekt", version.ref=  "detekt" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
room = { id = "androidx.room", version.ref = "room" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-compose-material3",
    "androidx-compose-material3-adaptive",
    "androidx-compose-material3-adaptive-layout",
    "androidx-material-icons-extended",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
]
compose-debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest",
]
glance = [
    "androidx-glance-appwidget",
    "androidx-glance-material3"
]
koin = [
    "koin-core",
    "koin-android",
    "koin-android-workmanager"
]
koin-compose = [
    "koin-core",
    "koin-android",
    "koin-android-workmanager",
    "koin-androidx-compose"
]
ktor = [
    "ktor-client-auth",
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json"
]